# Generated by Django 3.2.7 on 2022-09-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctorimageviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimagemodel',
            name='type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
