# Generated by Django 3.2.7 on 2022-09-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userimagemodel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimagemodel',
            old_name='type',
            new_name='type1',
        ),
    ]
