# Generated by Django 3.2.7 on 2022-09-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_type_userimagemodel_type1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimagemodel',
            name='type1',
        ),
    ]
