# Generated by Django 3.2.7 on 2022-09-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_userimagemodel_type1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorimageviewmodel',
            name='image',
            field=models.ImageField(upload_to='media/affected/'),
        ),
    ]
