# Generated by Django 3.2.7 on 2022-09-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_doctorimageviewmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorimageviewmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='doctorimageviewmodel',
            name='image1',
            field=models.ImageField(default=1, upload_to='affected/'),
            preserve_default=False,
        ),
    ]
