# Generated by Django 3.2.7 on 2022-09-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220923_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorImageViewModel',
        ),
        migrations.AddField(
            model_name='userimagemodel',
            name='type1',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
