# Generated by Django 3.2.7 on 2022-10-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220924_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorFeedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userimagemodel',
            name='type1',
            field=models.CharField(default='data', max_length=20),
        ),
    ]
